// Code generated by protoc-gen-go. DO NOT EDIT.
// source: storage/storage.proto

package storage

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type User struct {
	UserName             string   `protobuf:"bytes,1,opt,name=UserName,proto3" json:"UserName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_d19ee265301e4d9b, []int{0}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (dst *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(dst, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

type InsertTweetRequest struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Content              string   `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InsertTweetRequest) Reset()         { *m = InsertTweetRequest{} }
func (m *InsertTweetRequest) String() string { return proto.CompactTextString(m) }
func (*InsertTweetRequest) ProtoMessage()    {}
func (*InsertTweetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_d19ee265301e4d9b, []int{1}
}
func (m *InsertTweetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InsertTweetRequest.Unmarshal(m, b)
}
func (m *InsertTweetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InsertTweetRequest.Marshal(b, m, deterministic)
}
func (dst *InsertTweetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InsertTweetRequest.Merge(dst, src)
}
func (m *InsertTweetRequest) XXX_Size() int {
	return xxx_messageInfo_InsertTweetRequest.Size(m)
}
func (m *InsertTweetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InsertTweetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InsertTweetRequest proto.InternalMessageInfo

func (m *InsertTweetRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *InsertTweetRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type InsertTweetReply struct {
	TID                  string   `protobuf:"bytes,1,opt,name=TID,proto3" json:"TID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InsertTweetReply) Reset()         { *m = InsertTweetReply{} }
func (m *InsertTweetReply) String() string { return proto.CompactTextString(m) }
func (*InsertTweetReply) ProtoMessage()    {}
func (*InsertTweetReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_d19ee265301e4d9b, []int{2}
}
func (m *InsertTweetReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InsertTweetReply.Unmarshal(m, b)
}
func (m *InsertTweetReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InsertTweetReply.Marshal(b, m, deterministic)
}
func (dst *InsertTweetReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InsertTweetReply.Merge(dst, src)
}
func (m *InsertTweetReply) XXX_Size() int {
	return xxx_messageInfo_InsertTweetReply.Size(m)
}
func (m *InsertTweetReply) XXX_DiscardUnknown() {
	xxx_messageInfo_InsertTweetReply.DiscardUnknown(m)
}

var xxx_messageInfo_InsertTweetReply proto.InternalMessageInfo

func (m *InsertTweetReply) GetTID() string {
	if m != nil {
		return m.TID
	}
	return ""
}

type GetFollowersRequest struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFollowersRequest) Reset()         { *m = GetFollowersRequest{} }
func (m *GetFollowersRequest) String() string { return proto.CompactTextString(m) }
func (*GetFollowersRequest) ProtoMessage()    {}
func (*GetFollowersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_d19ee265301e4d9b, []int{3}
}
func (m *GetFollowersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFollowersRequest.Unmarshal(m, b)
}
func (m *GetFollowersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFollowersRequest.Marshal(b, m, deterministic)
}
func (dst *GetFollowersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFollowersRequest.Merge(dst, src)
}
func (m *GetFollowersRequest) XXX_Size() int {
	return xxx_messageInfo_GetFollowersRequest.Size(m)
}
func (m *GetFollowersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFollowersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetFollowersRequest proto.InternalMessageInfo

func (m *GetFollowersRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type Tweet struct {
	UserId               string   `protobuf:"bytes,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	TID                  string   `protobuf:"bytes,2,opt,name=TID,proto3" json:"TID,omitempty"`
	Timestamp            int64    `protobuf:"varint,3,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	Content              string   `protobuf:"bytes,4,opt,name=Content,proto3" json:"Content,omitempty"`
	TimeMessage          string   `protobuf:"bytes,5,opt,name=TimeMessage,proto3" json:"TimeMessage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Tweet) Reset()         { *m = Tweet{} }
func (m *Tweet) String() string { return proto.CompactTextString(m) }
func (*Tweet) ProtoMessage()    {}
func (*Tweet) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_d19ee265301e4d9b, []int{4}
}
func (m *Tweet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tweet.Unmarshal(m, b)
}
func (m *Tweet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tweet.Marshal(b, m, deterministic)
}
func (dst *Tweet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tweet.Merge(dst, src)
}
func (m *Tweet) XXX_Size() int {
	return xxx_messageInfo_Tweet.Size(m)
}
func (m *Tweet) XXX_DiscardUnknown() {
	xxx_messageInfo_Tweet.DiscardUnknown(m)
}

var xxx_messageInfo_Tweet proto.InternalMessageInfo

func (m *Tweet) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Tweet) GetTID() string {
	if m != nil {
		return m.TID
	}
	return ""
}

func (m *Tweet) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Tweet) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *Tweet) GetTimeMessage() string {
	if m != nil {
		return m.TimeMessage
	}
	return ""
}

type GetFollowersReply struct {
	Tweets               []*Tweet `protobuf:"bytes,1,rep,name=tweets,proto3" json:"tweets,omitempty"`
	FollowingNumber      string   `protobuf:"bytes,2,opt,name=followingNumber,proto3" json:"followingNumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFollowersReply) Reset()         { *m = GetFollowersReply{} }
func (m *GetFollowersReply) String() string { return proto.CompactTextString(m) }
func (*GetFollowersReply) ProtoMessage()    {}
func (*GetFollowersReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_d19ee265301e4d9b, []int{5}
}
func (m *GetFollowersReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFollowersReply.Unmarshal(m, b)
}
func (m *GetFollowersReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFollowersReply.Marshal(b, m, deterministic)
}
func (dst *GetFollowersReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFollowersReply.Merge(dst, src)
}
func (m *GetFollowersReply) XXX_Size() int {
	return xxx_messageInfo_GetFollowersReply.Size(m)
}
func (m *GetFollowersReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFollowersReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetFollowersReply proto.InternalMessageInfo

func (m *GetFollowersReply) GetTweets() []*Tweet {
	if m != nil {
		return m.Tweets
	}
	return nil
}

func (m *GetFollowersReply) GetFollowingNumber() string {
	if m != nil {
		return m.FollowingNumber
	}
	return ""
}

type UserFollowed struct {
	UserName             string   `protobuf:"bytes,1,opt,name=UserName,proto3" json:"UserName,omitempty"`
	Isfollowed           bool     `protobuf:"varint,2,opt,name=Isfollowed,proto3" json:"Isfollowed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserFollowed) Reset()         { *m = UserFollowed{} }
func (m *UserFollowed) String() string { return proto.CompactTextString(m) }
func (*UserFollowed) ProtoMessage()    {}
func (*UserFollowed) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_d19ee265301e4d9b, []int{6}
}
func (m *UserFollowed) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserFollowed.Unmarshal(m, b)
}
func (m *UserFollowed) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserFollowed.Marshal(b, m, deterministic)
}
func (dst *UserFollowed) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserFollowed.Merge(dst, src)
}
func (m *UserFollowed) XXX_Size() int {
	return xxx_messageInfo_UserFollowed.Size(m)
}
func (m *UserFollowed) XXX_DiscardUnknown() {
	xxx_messageInfo_UserFollowed.DiscardUnknown(m)
}

var xxx_messageInfo_UserFollowed proto.InternalMessageInfo

func (m *UserFollowed) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *UserFollowed) GetIsfollowed() bool {
	if m != nil {
		return m.Isfollowed
	}
	return false
}

// Used for "Search Users" Page
type UserList struct {
	List                 []*UserFollowed `protobuf:"bytes,1,rep,name=List,proto3" json:"List,omitempty"`
	NextPage             bool            `protobuf:"varint,2,opt,name=NextPage,proto3" json:"NextPage,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *UserList) Reset()         { *m = UserList{} }
func (m *UserList) String() string { return proto.CompactTextString(m) }
func (*UserList) ProtoMessage()    {}
func (*UserList) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_d19ee265301e4d9b, []int{7}
}
func (m *UserList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserList.Unmarshal(m, b)
}
func (m *UserList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserList.Marshal(b, m, deterministic)
}
func (dst *UserList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserList.Merge(dst, src)
}
func (m *UserList) XXX_Size() int {
	return xxx_messageInfo_UserList.Size(m)
}
func (m *UserList) XXX_DiscardUnknown() {
	xxx_messageInfo_UserList.DiscardUnknown(m)
}

var xxx_messageInfo_UserList proto.InternalMessageInfo

func (m *UserList) GetList() []*UserFollowed {
	if m != nil {
		return m.List
	}
	return nil
}

func (m *UserList) GetNextPage() bool {
	if m != nil {
		return m.NextPage
	}
	return false
}

type GetUsersRequest struct {
	LoggedInUserId       string   `protobuf:"bytes,1,opt,name=LoggedInUserId,proto3" json:"LoggedInUserId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUsersRequest) Reset()         { *m = GetUsersRequest{} }
func (m *GetUsersRequest) String() string { return proto.CompactTextString(m) }
func (*GetUsersRequest) ProtoMessage()    {}
func (*GetUsersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_d19ee265301e4d9b, []int{8}
}
func (m *GetUsersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUsersRequest.Unmarshal(m, b)
}
func (m *GetUsersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUsersRequest.Marshal(b, m, deterministic)
}
func (dst *GetUsersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUsersRequest.Merge(dst, src)
}
func (m *GetUsersRequest) XXX_Size() int {
	return xxx_messageInfo_GetUsersRequest.Size(m)
}
func (m *GetUsersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUsersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUsersRequest proto.InternalMessageInfo

func (m *GetUsersRequest) GetLoggedInUserId() string {
	if m != nil {
		return m.LoggedInUserId
	}
	return ""
}

type GetUsersResponse struct {
	Users                []*UserFollowed `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	NextPage             bool            `protobuf:"varint,2,opt,name=NextPage,proto3" json:"NextPage,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GetUsersResponse) Reset()         { *m = GetUsersResponse{} }
func (m *GetUsersResponse) String() string { return proto.CompactTextString(m) }
func (*GetUsersResponse) ProtoMessage()    {}
func (*GetUsersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_d19ee265301e4d9b, []int{9}
}
func (m *GetUsersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUsersResponse.Unmarshal(m, b)
}
func (m *GetUsersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUsersResponse.Marshal(b, m, deterministic)
}
func (dst *GetUsersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUsersResponse.Merge(dst, src)
}
func (m *GetUsersResponse) XXX_Size() int {
	return xxx_messageInfo_GetUsersResponse.Size(m)
}
func (m *GetUsersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUsersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUsersResponse proto.InternalMessageInfo

func (m *GetUsersResponse) GetUsers() []*UserFollowed {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *GetUsersResponse) GetNextPage() bool {
	if m != nil {
		return m.NextPage
	}
	return false
}

type FollowUserRequest struct {
	UserName             string   `protobuf:"bytes,1,opt,name=userName,proto3" json:"userName,omitempty"`
	UserNames            []string `protobuf:"bytes,2,rep,name=userNames,proto3" json:"userNames,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FollowUserRequest) Reset()         { *m = FollowUserRequest{} }
func (m *FollowUserRequest) String() string { return proto.CompactTextString(m) }
func (*FollowUserRequest) ProtoMessage()    {}
func (*FollowUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_d19ee265301e4d9b, []int{10}
}
func (m *FollowUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FollowUserRequest.Unmarshal(m, b)
}
func (m *FollowUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FollowUserRequest.Marshal(b, m, deterministic)
}
func (dst *FollowUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FollowUserRequest.Merge(dst, src)
}
func (m *FollowUserRequest) XXX_Size() int {
	return xxx_messageInfo_FollowUserRequest.Size(m)
}
func (m *FollowUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FollowUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FollowUserRequest proto.InternalMessageInfo

func (m *FollowUserRequest) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *FollowUserRequest) GetUserNames() []string {
	if m != nil {
		return m.UserNames
	}
	return nil
}

type FollowUserResponse struct {
	Status               bool     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FollowUserResponse) Reset()         { *m = FollowUserResponse{} }
func (m *FollowUserResponse) String() string { return proto.CompactTextString(m) }
func (*FollowUserResponse) ProtoMessage()    {}
func (*FollowUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_d19ee265301e4d9b, []int{11}
}
func (m *FollowUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FollowUserResponse.Unmarshal(m, b)
}
func (m *FollowUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FollowUserResponse.Marshal(b, m, deterministic)
}
func (dst *FollowUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FollowUserResponse.Merge(dst, src)
}
func (m *FollowUserResponse) XXX_Size() int {
	return xxx_messageInfo_FollowUserResponse.Size(m)
}
func (m *FollowUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FollowUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FollowUserResponse proto.InternalMessageInfo

func (m *FollowUserResponse) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func init() {
	proto.RegisterType((*User)(nil), "storage.User")
	proto.RegisterType((*InsertTweetRequest)(nil), "storage.InsertTweetRequest")
	proto.RegisterType((*InsertTweetReply)(nil), "storage.InsertTweetReply")
	proto.RegisterType((*GetFollowersRequest)(nil), "storage.GetFollowersRequest")
	proto.RegisterType((*Tweet)(nil), "storage.Tweet")
	proto.RegisterType((*GetFollowersReply)(nil), "storage.GetFollowersReply")
	proto.RegisterType((*UserFollowed)(nil), "storage.userFollowed")
	proto.RegisterType((*UserList)(nil), "storage.UserList")
	proto.RegisterType((*GetUsersRequest)(nil), "storage.GetUsersRequest")
	proto.RegisterType((*GetUsersResponse)(nil), "storage.GetUsersResponse")
	proto.RegisterType((*FollowUserRequest)(nil), "storage.FollowUserRequest")
	proto.RegisterType((*FollowUserResponse)(nil), "storage.FollowUserResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// StorageClient is the client API for Storage service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StorageClient interface {
	InsertTweets(ctx context.Context, in *InsertTweetRequest, opts ...grpc.CallOption) (*InsertTweetReply, error)
	GetFollowersTweets(ctx context.Context, in *GetFollowersRequest, opts ...grpc.CallOption) (*GetFollowersReply, error)
	GetAllUsers(ctx context.Context, in *GetUsersRequest, opts ...grpc.CallOption) (*GetUsersResponse, error)
	FollowUser(ctx context.Context, in *FollowUserRequest, opts ...grpc.CallOption) (*FollowUserResponse, error)
}

type storageClient struct {
	cc *grpc.ClientConn
}

func NewStorageClient(cc *grpc.ClientConn) StorageClient {
	return &storageClient{cc}
}

func (c *storageClient) InsertTweets(ctx context.Context, in *InsertTweetRequest, opts ...grpc.CallOption) (*InsertTweetReply, error) {
	out := new(InsertTweetReply)
	err := c.cc.Invoke(ctx, "/storage.Storage/InsertTweets", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageClient) GetFollowersTweets(ctx context.Context, in *GetFollowersRequest, opts ...grpc.CallOption) (*GetFollowersReply, error) {
	out := new(GetFollowersReply)
	err := c.cc.Invoke(ctx, "/storage.Storage/GetFollowersTweets", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageClient) GetAllUsers(ctx context.Context, in *GetUsersRequest, opts ...grpc.CallOption) (*GetUsersResponse, error) {
	out := new(GetUsersResponse)
	err := c.cc.Invoke(ctx, "/storage.Storage/GetAllUsers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageClient) FollowUser(ctx context.Context, in *FollowUserRequest, opts ...grpc.CallOption) (*FollowUserResponse, error) {
	out := new(FollowUserResponse)
	err := c.cc.Invoke(ctx, "/storage.Storage/FollowUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StorageServer is the server API for Storage service.
type StorageServer interface {
	InsertTweets(context.Context, *InsertTweetRequest) (*InsertTweetReply, error)
	GetFollowersTweets(context.Context, *GetFollowersRequest) (*GetFollowersReply, error)
	GetAllUsers(context.Context, *GetUsersRequest) (*GetUsersResponse, error)
	FollowUser(context.Context, *FollowUserRequest) (*FollowUserResponse, error)
}

func RegisterStorageServer(s *grpc.Server, srv StorageServer) {
	s.RegisterService(&_Storage_serviceDesc, srv)
}

func _Storage_InsertTweets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InsertTweetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServer).InsertTweets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/storage.Storage/InsertTweets",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServer).InsertTweets(ctx, req.(*InsertTweetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Storage_GetFollowersTweets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFollowersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServer).GetFollowersTweets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/storage.Storage/GetFollowersTweets",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServer).GetFollowersTweets(ctx, req.(*GetFollowersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Storage_GetAllUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServer).GetAllUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/storage.Storage/GetAllUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServer).GetAllUsers(ctx, req.(*GetUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Storage_FollowUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FollowUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServer).FollowUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/storage.Storage/FollowUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServer).FollowUser(ctx, req.(*FollowUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Storage_serviceDesc = grpc.ServiceDesc{
	ServiceName: "storage.Storage",
	HandlerType: (*StorageServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InsertTweets",
			Handler:    _Storage_InsertTweets_Handler,
		},
		{
			MethodName: "GetFollowersTweets",
			Handler:    _Storage_GetFollowersTweets_Handler,
		},
		{
			MethodName: "GetAllUsers",
			Handler:    _Storage_GetAllUsers_Handler,
		},
		{
			MethodName: "FollowUser",
			Handler:    _Storage_FollowUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "storage/storage.proto",
}

func init() { proto.RegisterFile("storage/storage.proto", fileDescriptor_storage_d19ee265301e4d9b) }

var fileDescriptor_storage_d19ee265301e4d9b = []byte{
	// 552 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0xdb, 0x6e, 0xd3, 0x40,
	0x10, 0xad, 0x93, 0x34, 0x97, 0x49, 0x68, 0xd3, 0x41, 0xad, 0x8c, 0x5b, 0xa1, 0xb0, 0x42, 0x55,
	0xb8, 0x28, 0x48, 0xe1, 0x05, 0x1e, 0x29, 0x15, 0x21, 0xa8, 0x8d, 0x52, 0x13, 0x9e, 0x78, 0x72,
	0x9b, 0xa9, 0x15, 0xc9, 0xb1, 0x8d, 0x67, 0xa3, 0xb6, 0xdf, 0xc0, 0xef, 0xf0, 0x81, 0x68, 0xd7,
	0x6b, 0xc7, 0x49, 0x43, 0xc4, 0xd3, 0x7a, 0x6e, 0xe7, 0x9c, 0x99, 0xd9, 0x35, 0x1c, 0xb2, 0x8c,
	0x12, 0xcf, 0xa7, 0x77, 0xe6, 0xec, 0xc5, 0x49, 0x24, 0x23, 0xac, 0x19, 0x53, 0x08, 0xa8, 0xfc,
	0x60, 0x4a, 0xd0, 0x81, 0xba, 0x3a, 0x47, 0xde, 0x9c, 0x6c, 0xab, 0x63, 0x75, 0x1b, 0x6e, 0x6e,
	0x8b, 0x2b, 0xc0, 0x61, 0xc8, 0x94, 0xc8, 0xc9, 0x1d, 0x91, 0x74, 0xe9, 0xd7, 0x82, 0x58, 0xe2,
	0x0b, 0xa8, 0x2c, 0x98, 0x12, 0x9d, 0xdd, 0xec, 0x3f, 0xe9, 0x65, 0x04, 0xaa, 0xcc, 0xd5, 0x21,
	0xb4, 0xa1, 0x76, 0x13, 0x85, 0x92, 0x42, 0x69, 0x97, 0x34, 0x66, 0x66, 0x8a, 0x97, 0xd0, 0x5e,
	0x81, 0x8c, 0x83, 0x07, 0x6c, 0x43, 0x79, 0x32, 0x3c, 0x37, 0xec, 0xea, 0x53, 0x7c, 0x80, 0xa7,
	0x03, 0x92, 0x5f, 0xa2, 0x20, 0x88, 0xee, 0x28, 0xe1, 0xff, 0x67, 0x16, 0xbf, 0x2d, 0xd8, 0xd5,
	0xd0, 0x78, 0x04, 0x55, 0xe5, 0x1f, 0x4e, 0x0d, 0xb0, 0xb1, 0x32, 0xb6, 0x52, 0xce, 0x86, 0x27,
	0xd0, 0x98, 0xcc, 0xe6, 0xc4, 0xd2, 0x9b, 0xc7, 0x76, 0xb9, 0x63, 0x75, 0xcb, 0xee, 0xd2, 0xa1,
	0x7a, 0xf9, 0x6c, 0x7a, 0xa9, 0xa4, 0xbd, 0x18, 0x13, 0x3b, 0xd0, 0x54, 0x69, 0x97, 0xc4, 0xec,
	0xf9, 0x64, 0xef, 0xea, 0x68, 0xd1, 0x25, 0x08, 0x0e, 0x56, 0xfb, 0x50, 0xed, 0x9e, 0x42, 0x55,
	0x2a, 0x85, 0x6c, 0x5b, 0x9d, 0x72, 0xb7, 0xd9, 0xdf, 0xcb, 0xfb, 0x48, 0x67, 0x62, 0xa2, 0xd8,
	0x85, 0xfd, 0x5b, 0x5d, 0x39, 0x0b, 0xfd, 0xd1, 0x62, 0x7e, 0x4d, 0x89, 0x11, 0xbd, 0xee, 0x16,
	0xdf, 0xa0, 0xa5, 0x9a, 0x37, 0x3c, 0xd3, 0x6d, 0x3b, 0xc5, 0xe7, 0x00, 0x43, 0xbe, 0x35, 0x99,
	0x1a, 0xb0, 0xee, 0x16, 0x3c, 0xe2, 0x2a, 0xad, 0xbd, 0x98, 0xb1, 0xc4, 0x57, 0x50, 0x51, 0xa7,
	0xd1, 0x79, 0x98, 0xeb, 0x2c, 0x92, 0xb9, 0x3a, 0x45, 0x51, 0x8e, 0xe8, 0x5e, 0x8e, 0xd5, 0x20,
	0x52, 0xd0, 0xdc, 0x16, 0x1f, 0x61, 0x7f, 0x40, 0x52, 0xa1, 0xe6, 0x9b, 0x3c, 0x85, 0xbd, 0x8b,
	0xc8, 0xf7, 0x69, 0x3a, 0x0c, 0x57, 0x96, 0xb4, 0xe6, 0x15, 0x3f, 0xa1, 0xbd, 0x2c, 0xe5, 0x38,
	0x0a, 0x99, 0xf0, 0x0d, 0xec, 0x2a, 0x01, 0xbc, 0x5d, 0x56, 0x9a, 0xb3, 0x55, 0xd7, 0x25, 0x1c,
	0xa4, 0xe9, 0xfa, 0xfe, 0x18, 0x65, 0x0e, 0xd4, 0x17, 0x6b, 0xb3, 0xcb, 0x6c, 0x75, 0x51, 0xb2,
	0x6f, 0xb6, 0x4b, 0x9d, 0x72, 0xb7, 0xe1, 0x2e, 0x1d, 0xe2, 0x2d, 0x60, 0x11, 0xce, 0xa8, 0x3d,
	0x82, 0x2a, 0x4b, 0x4f, 0x2e, 0x58, 0xa3, 0xd5, 0x5d, 0x63, 0xf5, 0xff, 0x94, 0xa0, 0xf6, 0x3d,
	0x15, 0x8e, 0x5f, 0xa1, 0x55, 0x78, 0x14, 0x8c, 0xc7, 0x79, 0x4b, 0x8f, 0x9f, 0x9f, 0xf3, 0x6c,
	0x73, 0x30, 0x0e, 0x1e, 0xc4, 0x0e, 0x8e, 0x01, 0x8b, 0x17, 0xce, 0xe0, 0x9d, 0xe4, 0x25, 0x1b,
	0x5e, 0x95, 0xe3, 0xfc, 0x23, 0x9a, 0x22, 0x9e, 0x43, 0x73, 0x40, 0xf2, 0x53, 0x10, 0xe8, 0x25,
	0xa0, 0x5d, 0x4c, 0x2e, 0xae, 0xb4, 0xa0, 0x6b, 0x7d, 0x63, 0x62, 0x07, 0x07, 0x00, 0xcb, 0xd9,
	0xe0, 0x92, 0xf1, 0xd1, 0xfc, 0x9d, 0xe3, 0x8d, 0xb1, 0x0c, 0xe8, 0xec, 0x35, 0xd8, 0xb3, 0xa8,
	0xe7, 0x27, 0xf1, 0x4d, 0x8f, 0xee, 0xbd, 0x79, 0x1c, 0x10, 0x67, 0x05, 0x67, 0x2d, 0x33, 0xcf,
	0xb1, 0xfa, 0xd3, 0x8d, 0xad, 0xeb, 0xaa, 0xfe, 0xe5, 0xbd, 0xff, 0x1b, 0x00, 0x00, 0xff, 0xff,
	0xf4, 0x48, 0x33, 0x60, 0x0b, 0x05, 0x00, 0x00,
}
